// // app/layout.jsx (or app/(app)/layout.jsx)
// import { Geist, Geist_Mono } from 'next/font/google';
// import '../globals.css';
// import SideBar from '../components/SideBar';
// import NavBar from '../components/NavBar';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata = {
//   title: 'Stock Pulse',
//   description: 'Generated by Sellers Systems',
//   icons: { icon: '/favicon.png' },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-stockDark text-white`}
//       >
//         {/* Fixed sidebar (publishes --sp-sidebar-width from within SideBar when collapsed/expanded) */}
//         <SideBar />

//         {/* Main column shifts by CSS var so it stays flush with the sidebar in both states */}
//         <div className="app-shell">
//           <NavBar />
//           <main className="p-6">{children}</main>
//         </div>
//       </body>
//     </html>
//   );
// }

// app/layout.jsx (or app/(app)/layout.jsx)
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import SideBar from '../components/SideBar';
import NavBar from '../components/NavBar';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Stock Pulse',
  description: 'Generated by Sellers Systems',
  icons: { icon: '/favicon.png' },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-stockDark text-white`}
      >
        <div className="app-grid">
          {/* Full-width header row */}
          <NavBar />

          {/* Left column under the header (sticky inside the column) */}
          <aside className="hidden md:block sidebar-sticky">
            <SideBar />
          </aside>

          {/* Right column (main content) */}
          <main className="p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
