import { Geist, Geist_Mono } from 'next/font/google';
import './styles/globals.css';
import SideBar from '@/components/layout/SideBar';
import NavBar from '@/components/layout/NavBar';
import Providers from './providers';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Stock Pulse',
  description: 'Generated by Sellers Systems',
  icons: { icon: '/favicon.png' },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-stockDark text-white`}
      >
        <Providers>
          <div className="app-grid">
            {/* Full-width header row */}
            <NavBar />

            {/* Left column under the header (sticky inside the column) */}
            <aside className="hidden md:block sidebar-sticky">
              <SideBar />
            </aside>

            {/* Right column (main content) */}
            <main className="p-6">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
